/**
 * Workspace cleanup.
 *
 *   npm run clean            removes generated output (reports, traces, videos, downloads)
 *   npm run clean:auth       removes stored sessions only (.auth/)
 *   node scripts/clean.js --all
 *   node scripts/clean.js --dry-run   lists what would be removed
 *
 * Everything it touches is git-ignored and regenerated by the next run, so it
 * is always safe to call - typically before a fresh run or in a CI cache step.
 */
import fs from 'node:fs';
import path from 'node:path';
import { PATHS, fromRoot } from '../framework/utils/paths.js';

const flags = new Set(process.argv.slice(2).map((argument) => argument.replace(/^--/, '')));
const wants = (name) => flags.has(name);
const dryRun = wants('dry-run') || wants('dry');

/** Output directories produced by a test run. */
const OUTPUT_TARGETS = [
  PATHS.reports,
  fromRoot('test-results'),
  fromRoot('playwright-report'),
  fromRoot('blob-report'),
  fromRoot('downloads'),
];

/** Stored storageState sessions - removing them forces the next run to log in. */
const AUTH_TARGETS = [PATHS.authState];

function bytesOf(target) {
  const stats = fs.statSync(target);
  if (!stats.isDirectory()) return stats.size;
  return fs.readdirSync(target).reduce((total, entry) => total + bytesOf(path.join(target, entry)), 0);
}

function humanSize(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB'];
  let value = bytes / 1024;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${value.toFixed(1)} ${units[unitIndex]}`;
}

function remove(target) {
  if (!fs.existsSync(target)) return 0;
  const size = bytesOf(target);
  if (!dryRun) fs.rmSync(target, { recursive: true, force: true });
  const label = dryRun ? 'would remove' : 'removed';
  console.log(`  ${label}  ${path.relative(PATHS.root, target) || target}  (${humanSize(size)})`);
  return size;
}

const targets = [
  ...(wants('auth') && !wants('all') ? [] : OUTPUT_TARGETS),
  ...(wants('auth') || wants('all') ? AUTH_TARGETS : []),
];

console.log(`Cleaning ${wants('auth') && !wants('all') ? 'stored sessions' : 'generated output'}...`);

const freed = targets.reduce((total, target) => total + remove(target), 0);

if (freed === 0) console.log('Done - nothing to clean.');
else
  console.log(dryRun ? `Dry run - ${humanSize(freed)} would be freed.` : `Done - ${humanSize(freed)} freed.`);
